apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webserver-with-logs
  name: webserver
spec:
  volumes:
  - name: shared-logs 
    emptyDir: {} # Correct structure for emptyDir

  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - mountPath: /var/log/nginx
      name: shared-logs
    resources:
      # Limits are higher than requests
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  
  - name: sidecar-container
    image: ubuntu:latest
    command: ["sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"]
    volumeMounts:
    - mountPath: /var/log/nginx
      name: shared-logs
    resources:
      # Limits are higher than requests
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"