apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
  labels:
    app: volume-share-datacenter
spec:
  containers:
    - name: volume-container-datacenter-1
      image: debian:latest
      command: ["/bin/sh", "-c"]
      args: ["sleep 3600"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/news


    - name: volume-container-datacenter-2
      image: debian:latest
      command: ["/bin/sh", "-c"]
      args: ["sleep 3600"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/games
  volumes:
    - name: volume-share
      emptyDir: {}