apiVersion: v1
kind: Pod
metadata:
  labels:
    app: httpd_app
  name: pod-httpd
spec:
  containers:
  - image: httpd:latest
    name: httpd-container
    resources: 
      requests:
        cpu: "250m" # Guarantee 250 millicores of CPU for scheduling
        memory: "128Mi"  # Guarantee 128 Mebibytes of memory for scheduling
      limits:
        cpu: "500m" # Hard limit of half a CPU core (500 millicores)
        memory: "256Mi" # Hard limit of 256 Mebibytes of memory