apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: redis-slave
  template:
    metadata:
      labels:
        apps: redis-slave
    spec:
      containers:
        - name: slave-redis-nautilus
          image: gcr.io/google_samples/gb-redisslave:v3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
spec:
  selector: 
    apps: redis-slave
  ports:
    - port: 6379
      targetPort: 6379
