apiVersion: v1
kind: Pod
metadata:
  name: secret-nautilus
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: media
  containers:
  - image: debian:latest
    name: secret-container-nautilus
    command: ["sleep", "3600"]
    volumeMounts:
      - name: secret-volume
        mountPath: /opt/apps
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"